repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4  
    hooks:
      - id: ruff-format
        name: Ruff format
        entry: ruff format
        language: python
        types: [python]
        args: ["."]
      - id: ruff
        name: Ruff lint
        entry: ruff check
        language: python
        types: [python]
        args: ["."]
        additional_dependencies: []
  - repo: local
    hooks:
      # - id: run-tests
      #   name: Run full pytest suite on push
      #   entry: pytest
      #   language: system
      #   branches: ^main$       # only run on main branch
      #   pass_filenames: false
      #   args: ["--maxfail=1", "--disable-warnings"]
      #   stages: [pre-push]
      - id: run-tests
        name: Run full pytest suite on push to main
        entry: scripts/run-tests-on-main
        language: script
        pass_filenames: false
        stages: [pre-push]
