[project]
name = "numpygrad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.21",
    "ipdb>=0.13.13",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
]
